---
Name: robotsconfig
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Odorisioe\SilverStripe\RobotsTxt\Extensions\SiteConfigExtension

Odorisioe\SilverStripe\RobotsTxt\Extensions\SiteConfigExtension:
  defaultRobotsDotTxtPath: '/public'
